# Generated by Django 5.1.15 on 2026-06-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('title_tr', models.CharField(max_length=140)),
                ('title_en', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('rooms', 'Rooms'), ('hotel', 'Hotel'), ('beyoglu', 'Beyoglu'), ('details', 'Details')], default='hotel', max_length=30)),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('title_tr', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('subtitle_tr', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('button_text_tr', models.CharField(blank=True, max_length=80)),
                ('button_text_en', models.CharField(blank=True, max_length=80)),
                ('button_url', models.CharField(blank=True, max_length=220)),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title_tr', models.CharField(max_length=140)),
                ('title_en', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('short_description_tr', models.TextField()),
                ('short_description_en', models.TextField()),
                ('full_description_tr', models.TextField()),
                ('full_description_en', models.TextField()),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('bed_type_tr', models.CharField(max_length=120)),
                ('bed_type_en', models.CharField(max_length=120)),
                ('size', models.CharField(blank=True, max_length=40)),
                ('features_tr', models.TextField(help_text='Virgülle ayırın.')),
                ('features_en', models.TextField(help_text='Separate with commas.')),
                ('price', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='Short icon label, e.g. wifi, coffee', max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title_tr', models.CharField(max_length=140)),
                ('title_en', models.CharField(max_length=140)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Rumelihan Hotel', max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('whatsapp', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_tr', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('google_maps_embed', models.TextField(blank=True)),
                ('google_maps_link', models.URLField(blank=True)),
                ('footer_text_tr', models.TextField(blank=True)),
                ('footer_text_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('text_tr', models.TextField()),
                ('text_en', models.TextField()),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/gallery/')),
                ('alt_text_tr', models.CharField(blank=True, max_length=160)),
                ('alt_text_en', models.CharField(blank=True, max_length=160)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='hotel.room')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
    ]
