# Generated by Django 5.1.15 on 2026-06-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('title_tr', models.CharField(max_length=140)),
                ('title_en', models.CharField(max_length=140)),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('page', models.CharField(choices=[('rooms', 'Rooms'), ('contact', 'Contact'), ('general', 'General')], default='general', max_length=30)),
                ('question_tr', models.CharField(max_length=220)),
                ('question_en', models.CharField(max_length=220)),
                ('answer_tr', models.TextField()),
                ('answer_en', models.TextField()),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NearbyAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('title_tr', models.CharField(max_length=140)),
                ('title_en', models.CharField(max_length=140)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('distance_tr', models.CharField(blank=True, max_length=80)),
                ('distance_en', models.CharField(blank=True, max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='attractions/')),
            ],
            options={
                'ordering': ['ordering', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowcaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(default='Tarihin Zarafetiyle Konaklayın', max_length=180)),
                ('title_en', models.CharField(default='Stay in the Elegance of History', max_length=180)),
                ('subtitle_tr', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='showcase/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
