# Generated by Django 5.1.15 on 2026-06-25 17:46

from django.db import migrations, models


def create_discount_campaign(apps, schema_editor):
    DiscountCampaign = apps.get_model('hotel', 'DiscountCampaign')
    DiscountCampaign.objects.update_or_create(
        pk=1,
        defaults={
            'title_tr': '1 Aylık Özel İndirim',
            'title_en': 'One-Month Special Offer',
            'message_tr': 'Tüm odalarda 1 ay boyunca %20 indirim fırsatı.',
            'message_en': 'Enjoy 20% off all rooms for one month.',
            'badge_text_tr': '%20 İndirim',
            'badge_text_en': '20% Off',
            'button_text_tr': 'Rezervasyon Talebi',
            'button_text_en': 'Request Reservation',
            'active': True,
            'show_popup': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_update_site_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(default='1 Aylık Özel İndirim', max_length=160)),
                ('title_en', models.CharField(default='One-Month Special Offer', max_length=160)),
                ('message_tr', models.TextField(default='Tüm odalarda 1 ay boyunca %20 indirim fırsatı.')),
                ('message_en', models.TextField(default='Enjoy 20% off all rooms for one month.')),
                ('badge_text_tr', models.CharField(default='%20 İndirim', max_length=80)),
                ('badge_text_en', models.CharField(default='20% Off', max_length=80)),
                ('button_text_tr', models.CharField(default='Rezervasyon Talebi', max_length=80)),
                ('button_text_en', models.CharField(default='Request Reservation', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('show_popup', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discount Campaign',
                'verbose_name_plural': 'Discount Campaign',
            },
        ),
        migrations.RunPython(create_discount_campaign, migrations.RunPython.noop),
    ]
